blueprint:
  name: Gestion de la recharge de la voiture électrique
  description: Gère la recharge de la voiture électrique en fonction du mode sélectionné.
  domain: automation
  input:
    charge_mode_selector:
      name: Sélecteur de mode de charge
      description: L'entité input_select qui contrôle le mode de charge.
      selector:
        entity:
          domain: input_select
    solar_optimizer_switch:
      name: Interrupteur Solar Optimizer
      description: L'entité switch qui active/désactive le Solar Optimizer.
      selector:
        entity:
          domain: switch
    solar_optimizer_tesla_recharge:
      name: Interrupteur Solar Optimizer Tesla Recharge
      description: L'entité switch qui lance la recharge via Solar Optimizer.
      selector:
        entity:
          domain: switch
    tesla_ble_charger:
      name: Interrupteur Tesla BLE Charger
      description: L'entité switch qui contrôle la recharge Tesla BLE.
      selector:
        entity:
          domain: switch
    tesla_ble_charging_current:
      name: Courant de charge Tesla BLE
      description: L'entité number qui contrôle l'ampérage de la charge.
      selector:
        entity:
          domain: number
    tesla_ble_charging_limit:
      name: Limite de charge Tesla BLE
      description: L'entité number qui définit la limite de charge.
      selector:
        entity:
          domain: number
    tesla_charge_limit_soc:
      name: Limite de charge SOC Tesla
      description: L'entité sensor qui indique le niveau de charge maximum souhaité.
      selector:
        entity:
          domain: sensor
    tesla_usable_battery_level:
      name: Niveau de batterie utilisable Tesla
      description: L'entité sensor qui indique le niveau de batterie actuel.
      selector:
        entity:
          domain: sensor
    tesla_plugged_in:
      name: Tesla branchée
      description: L'entité binary_sensor qui indique si la Tesla est branchée.
      selector:
        entity:
          domain: binary_sensor
    tesla_ble_presence:
      name: Présence Tesla BLE
      description: L'entité binary_sensor qui indique si la Tesla est présente.
      selector:
        entity:
          domain: binary_sensor
    charge_limit:
      name: Limite de charge
      description: L'entité input_number qui définit la limite de charge souhaitée.
      selector:
        entity:
          domain: input_number
    to_q_sy2_jzt:
      name: Interrupteur alimentation chargeur
      description: L'entité switch qui contrôle l'alimentation du chargeur.
      selector:
        entity:
          domain: switch

trigger:
  - platform: time
    at: "22:00:00"
  - platform: time
    at: "06:00:00"
  - platform: state
    entity_id: !input charge_mode_selector
  - platform: state
    entity_id: !input tesla_plugged_in
    to: "on"
  - platform: state
    entity_id: !input tesla_ble_presence
    to: "on"
  - platform: numeric_state
    entity_id: !input tesla_usable_battery_level
    below: !input charge_limit

condition:
  - condition: template
    value_template: "{{ states('input_select.charge_mode') in ['Solaire', 'Nuit', 'Manuel', 'Sans charge'] }}"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input charge_mode_selector
            state: "Solaire"
          - condition: time
            after: "07:00:00"
            before: "20:00:00"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input solar_optimizer_switch
          - service: switch.turn_on
            target:
              entity_id: !input to_q_sy2_jzt
      - conditions:
          - condition: state
            entity_id: !input charge_mode_selector
            state: "Nuit"
          - condition: time
            after: "22:00:00"
            before: "06:00:00"
          - condition: template
            value_template: "{{ states(!input tesla_charge_limit_soc) | float < states(!input charge_limit) | float }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input solar_optimizer_switch
          - service: number.set_value
            target:
              entity_id: !input tesla_ble_charging_current
            data:
              value: 16
          - service: switch.turn_on
            target:
              entity_id: !input to_q_sy2_jzt
          - service: switch.turn_on
            target:
              entity_id: !input tesla_ble_charger
      - conditions:
          - condition: state
            entity_id: !input charge_mode_selector
            state: "Manuel"
          - condition: template
            value_template: "{{ states(!input tesla_charge_limit_soc) | float < states(!input charge_limit) | float }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input solar_optimizer_switch
          - service: number.set_value
            target:
              entity_id: !input tesla_ble_charging_current
            data:
              value: 16
          - service: switch.turn_on
            target:
              entity_id: !input to_q_sy2_jzt
          - service: switch.turn_on
            target:
              entity_id: !input tesla_ble_charger
      - conditions:
          - condition: state
            entity_id: !input charge_mode_selector
            state: "Sans charge"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input solar_optimizer_switch
          - service: switch.turn_off
            target:
              entity_id: !input tesla_ble_charger
          - delay: "00:05:00"
          - service: switch.turn_off
            target:
              entity_id: !input to_q_sy2_jzt
